version: '3'

services:
  antenna_client:
    build: ./
    image: antenna_client
    container_name: antenna_client
    volumes:
      - ./:/antenna
    ports:
      - "80:8080"
    environment:
      # SERVER接口地址
      SERVER_URL: "http://test.com"
    networks:
      - antenna_client

networks:
  antenna_client:
    driver: bridge
